# -*- coding: utf-8 -*-
"""curso_python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cw5z2acF4NJvpk1Xi4qoM-PP1ZmDoAh5
"""

var = "10.80 + 5.15"
print(type(var))

print(type('10'+'4'))

#print('Michelle quero '+10+'pontos')
#NAO PODE CONCATENAR TIPOS DE VARIAVEIS DIFERENTES#

print('Michelle quero',10,'pontos')

nome = 'mari'
sobrenome = 'linda'
idade = 18
peso = 60.5

print('A '+ nome, sobrenome +' tem', idade, 'anos e pesa', peso)

nome = input('Qual seu nome? ')
print('Prazer em te conhecer', nome)

nota = float(input('Qual foi sua nota? '))

if nota>=8:
    print('parabéns!!!')
elif nota< 8 and nota>6:
    print('você pode melhorar!!!')
else:
    print('estude mais!!!')


# O que acontece se eu passar a nota 8????

# 1) Receba dois números e mostre a soma deles
num1 = float(input('Informe o primeiro número?'))
num2 = float(input('Informe o segundo número?'))

soma = num1 + num2

print(soma)

from google.colab import drive
drive.mount('/content/drive')

# 2) Criar um script que receba o dia, mês e ano de nascimento da pessoa e mostre em tela

dia = input('Informe o dia:')
mes = input('Informe o mes:')
ano = input('Informe o ano:')

print('Data de nascimento:', dia ,'/',mes,'/',ano)

# 3) Criar um Script que pergunta o nome, idade, sobrenome, peso
# falar se a pessoa pode votar
# pode tirar carteira
# pode tomar vacina
# se é maior ou não de idade
# se é idosa ou não 60+

nome =  input('Informe o nome:')
idade = int(input('Informe a idade:'))
sobre = input('Informe o sobre:')
peso = float(input('Informe o peso:'))

if idade >= 16:
  print('Pode votar')
elif idade > 18:
  print('Pode tirar carteira')
  print('Maior de idade')
elif idade > 60:
  print('Idosa')
else:
  print('Pode vacinar')

#Diferentes formas de concatenar variáveis
nome = 'Paulo'
sobrenome = 'Gordinho'

print(f'Prazer em te conehcer {nome} {sobrenome}!')
print('Prazer em te conehcer {} {}!'.format(nome, sobrenome))

# True False
# Objeto e métodos

n = input('Digite: ')

print("É número:", n.isnumeric())
print("É apenas letras:", n.isalpha())
print("Tem letras e números:", n.isalnum())
print("É apenas maiúscula:", n.isupper())
print("É apenas minúscula:", n.islower())
print("É string: ", isinstance(n, str))
print("É boolean: ", isinstance(n, bool))
print("Só tem espaço: ", n.isspace())
print("O tipo é: ", type(n))

# 4) Descubra se o número é float

numero = input('Número: ')

print("O número é float: ", isinstance(numero, float))

# Operador de Adição
a = 10
b = 5
soma = a + b
print(f"Soma: {soma}")

# Operador de Subtração
subtracao = a - b
print(f"Subtração: {subtracao}")

# Operador de Multiplicação
multiplicacao = a * b
print(f"Multiplicação: {multiplicacao}")

# Operador de Divisão
divisao = a / b
print(f"Divisão: {divisao}")

# Operador de Divisão Inteira
divisao_inteira = a // b
print(f"Divisão Inteira: {divisao_inteira}")

# Operador de Resto da Divisão (Módulo)
resto_divisao = a % b
print(f"Resto da Divisão (Módulo): {resto_divisao}")

# Operador de Exponenciação
exponenciacao = a ** b
print(f"Exponenciação: {exponenciacao}")

# 5) Mostre o antecessor e o sucessor de um número

numero = float(input('Informe um número: '))

antecessor = numero-1
sucessor = numero+1

print(f"Antecessor: {antecessor}")
print(f"Sucessor: {sucessor}")

# 6) Solicite 3 números e me devolva a média

num1 = float(input('Primeiro número: '))
num2 = float(input('Segundo número: '))
num3 = float(input('Terceiro número: '))

soma = num1 + num2 + num3
media = soma/3

print(f"A média dos números é: {media}")

# 7) Solicite um número e me devolva o dobro, triplo, metade e raiz

import math

num = float(input('Número: '))

dobro = num * 2
triplo = num * 3
metade = num / 2
raiz = num ** (1/2)
raiz2 = math.sqrt(num)


print(f"Dobro: {dobro} | Triplo: {triplo} | Metade: {metade} | Raiz: {raiz2}")

# 8) Solicite a altura, largura e a quantidade de metros que um litro de tinta faz e me diga quantos litros de tintas serão necessários para pintar a parede

altura = float(input("Digite a altura da parede em metros:"))
largura = float(input("Digite a largura da parede em metros:"))

metros_quadrados_por_litro = float(input("Digite a quantidade de metros quadrados que um litro de tinta pinta:"))

area_da_parede = altura * largura
litros_de_tinta_necessarios = area_da_parede / metros_quadrados_por_litro

print(f"Para pintar uma parede de {altura} metros de altura e {largura} metros de largura, serão necessários {litros_de_tinta_necessarios:.2f} litros de tinta.")

# 9) Solicite o valor do produto e a porcentagem de desconto e me mostre o valor final do produto

valor = float(input("Digite o valor do produto:"))
pdesconto = float(input("Digite o percentual de desconto(%):"))
desconto = (pdesconto / 100) * valor
valor_com_desconto = valor - desconto

print(f"O valor com {pdesconto}% de desconto é: R$ {valor_com_desconto:.2f}")

# 10) Solicite renda mensal e o histórico de crédito ao usuário e me diga se ele tem  o não condições para fazer um emprestimo
# historico pode ser perfeito, bom, ruim
# para estar apto: tem que ter o historico perfeito, ou uma renda maior que 100000, ou historio bom e uma renda maior que 2000

renda_mensal = float(input("Digite sua renda mensal (em R$): "))
historico_credito = input("Você tem um histórico de crédito bom? (perfeito, bom ou ruim): ").lower()

# Verifica a elegibilidade para o empréstimo
if renda_mensal >= 2000 and historico_credito == "bom":
    print("Parabéns! Você é elegível para um empréstimo.")
elif renda_mensal >= 100000 or historico_credito == "perfeito":
    print("Parabéns! Você é elegível para um empréstimo.")
else:
    print("Desculpe, você não é elegível para um empréstimo neste momento.")

# Repetição em python em python
num1 = input("Entre com um número: ")
num2 = input("Entre com um número: ")
num3 = input("Entre com um número: ")

print(f'Você digitou {num1}, {num2}, {num3}')

#stop
for n in range(3):
    print(n)

print()
#start, stop
for n in range(3, 10):
  print(n)

print()
#start, stop, incremento
x = range(3, 10, 2)
for n in x:
  print(n)

# E se eu quiser permitir que o usuário digita quantos números ele quiser e só pare quando ele digitar 10

# num = 0
# while num <= 100:
#     num = int(input("Digite um número: "))
#     print("valor é de")
#     print(num)

senha_correta = "12345"
senha = input("Digite a senha: ")
while senha != senha_correta:
    senha = input("Senha incorreta. Tente novamente: ")
print("Acesso permitido!")

# Se eu quiser somar o número até o total de 100?
total = 0
while total < 100:
    num = int(input("Digite um número: "))
    total += num
    print(f"Soma do valor é {total}")

# lisa em python

# Exemplo de uma lista de números inteiros
numeros = [1, 2, 3, 4, 5]

# Exemplo de uma lista de strings
frutas = ["maçã", "banana", "laranja"]

# for i in range(3):
#     print(frutas[i])


for i in frutas:
    print(i)

frutas = ["maçã", "banana", "laranja"]
primeira_fruta = frutas[0]  # Acessa a primeira fruta (maçã)
segunda_fruta = frutas[1]   # Acessa a segunda fruta (banana)

frutas = ["maçã", "banana", "laranja"]
frutas[2] = "pêra"  # Substitui "banana" por "pêra"

frutas = ["maçã", "banana"]
frutas.append("laranja")     # Adiciona "laranja" no final da lista
frutas.insert(1, "uva")      # Insere "uva" na posição 1 (entre "maçã" e "banana")

frutas = ["maçã", "banana", "laranja"]
frutas.remove("banana")  # Remove "banana" da lista
elemento_removido = frutas.pop(0)  # Remove o primeiro elemento ("maçã") e o armazena em 'elemento_removido'

# 11) como mostrar todos os valores de uma lista 1 por 1
lista = [1,2,3,4,5]

for i in lista:
  print(i)

# 12) mostrar o tamanho de uma lista

lista = ["bola", "quadrado", "triângulo"]

count = 0

for i in lista:
  count+=1

print(count)
print(len(lista))

# 13) Fazer um for onde eu vou entrar com 10 números, mas se eu digitar 0 eu saio do for

for i in range(10):
  numero = int(input('Informe um número: '))
  if numero == 0:
    break

# 14) Verificando a existência de um elemento:

lista = ["bola", "quadrado", "triângulo"]

pesquisa = input("Qual valor quer pesquisar?")

for i in lista:
  if i == pesquisa:
    print("Está na lista")
    break
  else:
    print("Não está na lista")

# 15) Como preencher uma lista até eu digitar 10000

lista = []
numero = 0
while numero != 10000:
    numero = int(input("Digite um número para adicionar à lista: "))
    lista.append(numero)

print("Lista preenchida:", lista)

# 16) Somar todos os valores de uma
def soma_lista(lista):
    soma = 0
    for numero in lista:
        soma += numero
    return soma

lista = [1, 2, 3, 4, 5]
resultado = soma_lista(lista)
print(f"A soma da lista é: {resultado}")

# 17) Fazer a média de uma lista
def media_lista(lista):
    soma = sum(lista)
    media = soma / len(lista)
    return media

lista = [10, 20, 30, 40, 50]
resultado = media_lista(lista)
print(f"A média da lista é: {resultado}")

# 18) Maior elemento de uma lista

def maior_elemento(lista):
    maior = lista[0]
    for numero in lista:
        if numero > maior:
            maior = numero
    return maior

lista = [15, 7, 38, 41, 12]
resultado = maior_elemento(lista)
print(f"O maior elemento da lista é: {resultado}")

# 19) Total de elementos de uma lista

def contar_elemento(lista, elemento):
    contagem = lista.count(elemento)
    return contagem

lista = [1, 2, 2, 3, 2, 4, 2, 5]
elemento = 2
resultado = contar_elemento(lista, elemento)
print(f"O elemento {elemento} aparece {resultado} vezes na lista.")

# 20) Iverter a ordem de uma lista

def inverter_lista(lista):
    lista_invertida = lista[::-1]
    return lista_invertida

lista = [1, 2, 3, 4, 5]
lista_invertida = inverter_lista(lista)
print(f"Lista original: {lista}")
print(f"Lista invertida: {lista_invertida}")

# 21) Escrevam um programa que solicite ao usuário um número e verifique se ele está presente em uma lista. O programa deve continuar pedindo até que o usuário insira "0" para sair.

while True:
    numero = int(input("Digite um número para verificar (ou 0 para sair): "))
    if numero == 0:
        break
    elif numero in lista:
        print(f"{numero} está presente na lista.")
    else:
        print(f"{numero} não está na lista.")

# 22) Criar um programa que permita ao usuário remover elementos específicos de uma lista até que eles decidam parar

while True:
    print("Lista atual:", lista)
    elemento = int(input("Digite o elemento a ser removido (ou 0 para parar): "))
    if elemento == 0:
        break
    if elemento in lista:
        lista.remove(elemento)
        print(f"{elemento} foi removido da lista.")
    else:
        print(f"{elemento} não está na lista. Nada foi removido.")

print("Lista final:", lista)

# 23) Escrevam um programa que permita ao usuário adicionar elementos a uma lista, garantindo que os elementos sejam únicos (não podem ser duplicados na lista)

while True:
    elemento = int(input("Digite um elemento para adicionar à lista (ou 0 para parar): "))
    if elemento == 0:
        break
    if elemento not in lista:
        lista.append(elemento)
        print(f"{elemento} foi adicionado à lista.")
    else:
        print(f"{elemento} já está na lista. Não foi adicionado novamente.")

# 24) Desafio para casa
# Adivinhar o número secreto: Crie um jogo onde o computador escolhe um número aleatório e o jogador tem que adivinhar o número. O programa deve fornecer dicas se o número digitado for muito alto ou muito baixo

import random

# Gerar um número aleatório entre 1 e 100
numero_secreto = random.randint(1, 100)

tentativas = 0

print("Bem-vindo ao jogo de adivinhar o número secreto!")
print("Tente adivinhar um número entre 1 e 100.")

while True:
    tentativa = int(input("Digite o seu palpite: "))
    tentativas += 1

    if tentativa < numero_secreto:
        print("O número é maior. Tente novamente.")
    elif tentativa > numero_secreto:
        print("O número é menor. Tente novamente.")
    else:
        print(f"Parabéns! Você acertou o número secreto {numero_secreto} em {tentativas} tentativas.")
        break

#25) enquanto o tamanho de uma lista for menor que 10

lista = []

while len(lista) < 10:
  lista.append(input('Insira um número: '))

lista